language: node_js
node_js:
  - 13

services:
  - docker

script:
  - docker --version # print the version for logging
  - cd $TRAVIS_BUILD_DIR/udagram-user-service
  - docker build -t "$DOCKER_USER"/udagram-user-service:latest .
  - cd $TRAVIS_BUILD_DIR/udagram-frontend
  - docker build -t "$DOCKER_USER"/udagram-feed-service:latest .
  - cd $TRAVIS_BUILD_DIR/udagram-frontend
  - docker build -t "$DOCKER_USER"/udagram-frontend:latest .

#stage:
#  - user
#  - feed
#  - frontend
#
#jobs:
#  include:
#    - stage: user
#      name: "user backend service"
#      script:
#        - echo "Starting user backend build"
#        - docker --version # print the version for logging
#        - docker build -t "$DOCKER_USER"/udagram-user-service:latest ./udagram-user-service
#      after_success:
#        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
#        - docker push "$DOCKER_USER"/udagram-user-service:lastest
#
#    - stage: feed
#        name: "feed backend service"
#        script:
#          - echo "Starting feed backend build"
#          - docker --version # print the version for logging
#          - docker build -t "$DOCKER_USER"/udagram-feed-service:latest ./udagram-feed-api
#        after_success:
#          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
#          - docker push "$DOCKER_USER"/udagram-feed-service:lastest
#
#    - stage: frontend
#        name: "frontend service"
#        script:
#          - echo "Starting frontend build"
#          - docker --version # print the version for logging
#          - docker build -t "$DOCKER_USER"/udagram-frontend:latest ./udagram-frontend
#        after_success:
#          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
#          - docker push "$DOCKER_USER"/udagram-frontend:lastest
