language: node_js
node_js:
  - 13

services:
  - docker

script:
  - docker --version # print the version for logging
  - cd $TRAVIS_BUILD_DIR/udagram-user-api
  - docker build -t "$DOCKER_USER"/udagram-user-service:latest .
  - cd $TRAVIS_BUILD_DIR/udagram-feed-api
  - docker build -t "$DOCKER_USER"/udagram-feed-service:latest .
  - cd $TRAVIS_BUILD_DIR/udagram-frontend
  - docker build -t "$DOCKER_USER"/udagram-frontend:latest .
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push "$DOCKER_USER"/udagram-user-service:latest
  - docker push "$DOCKER_USER"/udagram-feed-service:latest
  - docker push "$DOCKER_USER"/udagram-frontend:latest


#jobs:
#  include:
#    - stage: user
#      name: "user backend service"
#      script:
#        - echo "Starting user backend build"
#        - docker --version # print the version for logging
#        - cd $TRAVIS_BUILD_DIR/udagram-user-api
#        - docker build -t "$DOCKER_USER"/udagram-user-service:latest .
#      after_success:
#        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
#        - docker push "$DOCKER_USER"/udagram-user-service:latest
#
#    - stage: feed
#        name: "feed backend service"
#        script:
#          - echo "Starting feed backend build"
#          - docker --version # print the version for logging
#          - cd $TRAVIS_BUILD_DIR/udagram-feed-api
#          - docker build -t "$DOCKER_USER"/udagram-feed-service:latest .
#        after_success:
#          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
#          - docker push "$DOCKER_USER"/udagram-feed-service:latest
#
#    - stage: frontend
#        name: "frontend service"
#        script:
#          - echo "Starting frontend build"
#          - docker --version # print the version for logging
#          - cd $TRAVIS_BUILD_DIR/udagram-frontend
#          - docker build -t "$DOCKER_USER"/udagram-frontend:latest ./udagram-frontend
#        after_success:
#          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
#          - docker push "$DOCKER_USER"/udagram-frontend:latest
