language: node_js
node_js:
  - 13

services:
  - docker

script:
  - docker --version # print the version for logging
  - cd $TRAVIS_BUILD_DIR/udagram-feed-api
  - docker build -t "$DOCKER_USER"/udagram-user-service:0.4 .
  - cd $TRAVIS_BUILD_DIR/udagram-feed-service
  - docker build -t "$DOCKER_USER"/udagram-feed-service:0.5 .
  - cd $TRAVIS_BUILD_DIR/udagram-frontend
  - docker build -t "$DOCKER_USER"/udagram-frontend:0.3 .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push "$DOCKER_USER"/udagram-user-service:0.4
  - docker push "$DOCKER_USER"/udagram-feed-service:0.5
  - docker push "$DOCKER_USER"/udagram-frontend:0.3
