language: node_js
node_js:
  - 13

services:
  - docker

stage:
  - user
  - feed
  - frontend

jobs:
  include:
    - stage: user
      name: "user backend service"
      script:
        - cd $TRAVIS_BUILD_DIR/udagram-user-api
        - echo pwd
        - docker --version # print the version for logging
        - docker build -t "$DOCKER_USER"/udagram-user-service:latest .
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
        - docker push "$DOCKER_USER"/udagram-user-service:lastest
        -
    - stage: feed
        name: "feed backend service"
        script:
          - cd $TRAVIS_BUILD_DIR/udagram-feed-api
          - echo pwd
          - docker --version # print the version for logging
          - docker build -t "$DOCKER_USER"/udagram-feed-service:latest .
        after_success:
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
          - docker push "$DOCKER_USER"/udagram-feed-service:lastest

    - stage: frontend
        name: "frontend service"
        script:
          - cd $TRAVIS_BUILD_DIR/udagram-frontend
          - echo pwd
          - docker --version # print the version for logging
          - docker build -t "$DOCKER_USER"/udagram-frontend:latest .
        after_success:
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
          - docker push "$DOCKER_USER"/udagram-frontend:lastest
