apiVersion: v1
kind: Service
metadata:
  name: udagram-feed-service
  labels:
    app: udagram-feed-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: udagram-feed-service
